# Generated by Django 3.0.4 on 2020-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_bd',
            name='network_Mac',
            field=models.CharField(default=0, help_text='Мак Сетевухи', max_length=200, verbose_name='Мак Адрес'),
            preserve_default=False,
        ),
    ]
