# Generated by Django 3.0.4 on 2020-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200317_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(help_text='Имя пользователя', max_length=200, verbose_name='Имя')),
                ('user_lastname', models.CharField(help_text='Фамилия пользователя', max_length=200, verbose_name='Фамилия')),
                ('user_secondname', models.CharField(help_text='Фамилия пользователя', max_length=200, verbose_name='Фамилия')),
                ('user_birth', models.DateField(help_text='Дата рождения', verbose_name='Дата рождения')),
                ('user_photo', models.ImageField(help_text='Фото пользователя', upload_to='', verbose_name='Фото')),
                ('user_dep', models.CharField(help_text='Департамент', max_length=500, verbose_name='Департамент')),
                ('user_otdel', models.CharField(help_text='Отдел пользователя', max_length=500, verbose_name='Отдел')),
                ('user_desc', models.TextField(help_text='Дополнительная информация', max_length=1000, verbose_name='Коментарии')),
            ],
        ),
    ]
