# Generated by Django 3.0.5 on 2020-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ad_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad_users',
            options={'verbose_name': 'Пользователя домена', 'verbose_name_plural': 'Доменные пользователи'},
        ),
        migrations.AlterModelOptions(
            name='inventory_bd',
            options={'verbose_name': 'Инвентаризация', 'verbose_name_plural': 'Раздел Инвентаризации'},
        ),
        migrations.AddField(
            model_name='services',
            name='service_name',
            field=models.CharField(default=1, help_text='Название сервиса', max_length=200, verbose_name='Сервис'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_owner',
            field=models.ForeignKey(default=1, on_delete=models.SET('Не определен'), to='inventory.Ad_users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad_users',
            name='user_secondname',
            field=models.CharField(help_text='Фамилия пользователя', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='inventory_bd',
            name='sum_ram',
            field=models.IntegerField(help_text='Сумма оперативки', verbose_name='ОЗУ'),
        ),
    ]
