# Generated by Django 3.0.5 on 2020-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200406_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AddField(
            model_name='ad_users',
            name='user_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email пользователя'),
            preserve_default=False,
        ),
    ]
