# Generated by Django 3.0.5 on 2020-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200406_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_users',
            name='user_profession',
            field=models.CharField(default=0, help_text='Должность пользователя', max_length=500, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad_users',
            name='user_photo',
            field=models.ImageField(help_text='Фото пользователя', upload_to='users/photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='inventory_bd',
            name='network_Mac',
            field=models.CharField(blank=True, help_text='Мак Сетевухи', max_length=200, verbose_name='Мак Адрес'),
        ),
        migrations.AlterField(
            model_name='inventory_bd',
            name='network_card',
            field=models.CharField(blank=True, help_text='Сетевуха', max_length=200, verbose_name='Сетевая карточка'),
        ),
        migrations.AlterField(
            model_name='inventory_bd',
            name='processor',
            field=models.CharField(blank=True, help_text='Проц', max_length=200, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='inventory_bd',
            name='ram_type',
            field=models.CharField(blank=True, help_text='Тип ОЗУ', max_length=200, verbose_name='Тип ОЗУ'),
        ),
        migrations.AlterField(
            model_name='inventory_bd',
            name='sum_ram',
            field=models.IntegerField(blank=True, help_text='Сумма оперативки', verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_owner',
            field=models.ForeignKey(blank=True, on_delete=models.SET('Не определен'), to='inventory.Ad_users'),
        ),
    ]
