# Generated by Django 3.0.5 on 2020-04-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='request',
            new_name='request_desc',
        ),
    ]
