# Generated by Django 3.0.5 on 2020-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0003_auto_20200416_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='number_access',
            field=models.IntegerField(help_text='Номер Заявки', verbose_name='Номер заявки'),
        ),
    ]
