# Generated by Django 3.0.5 on 2020-04-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0006_auto_20200416_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль Пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
