# Generated by Django 3.0.5 on 2020-04-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0007_auto_20200416_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
