# Generated by Django 3.0.5 on 2020-04-16 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Request_Access', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_last_name', models.CharField(help_text='Фамилия', max_length=200, verbose_name='Фамилия')),
                ('user_first_name', models.CharField(help_text='Имя', max_length=200, verbose_name='Имя')),
                ('user_secondname', models.CharField(help_text='Отчество', max_length=200, verbose_name='Отчество')),
                ('user_dep', models.CharField(help_text='Департамент', max_length=200, verbose_name='Департамент')),
                ('user_otdel', models.CharField(help_text='Отдел', max_length=200, verbose_name='Отдел')),
                ('user_email', models.EmailField(help_text='Email', max_length=254, verbose_name='Почтовый адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль Пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
