# Generated by Django 3.0.5 on 2020-04-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0010_auto_20200416_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='request_statuser',
            field=models.CharField(choices=[('на согласовании', 'На согласовании'), ('согласовано', 'Согласовано'), ('отказ', 'Заявка отклонена'), ('ошибка', 'Ошибка'), ('Пипос', 'Пипос')], default='на согласовании', max_length=15),
        ),
    ]
