# Generated by Django 3.0.5 on 2020-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0011_access_request_statuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='request_statuser',
            field=models.CharField(choices=[('На согласовании', 'На согласовании'), ('Согласовано', 'Согласовано'), ('Отказ', 'Заявка отклонена'), ('Ошибка', 'Ошибка'), ('Пипос', 'Пипос')], default='На согласовании', max_length=15),
        ),
    ]
