# Generated by Django 3.0.5 on 2020-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0014_auto_20200419_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.RemoveField(
            model_name='access',
            name='number_access',
        ),
        migrations.RemoveField(
            model_name='access',
            name='user_dir',
        ),
        migrations.AddField(
            model_name='access',
            name='user_boss',
            field=models.CharField(blank=True, help_text='Руководитель пользователя', max_length=200, null=True, verbose_name='Руководитель пользователя'),
        ),
        migrations.AddField(
            model_name='access',
            name='user_dep',
            field=models.CharField(blank=True, help_text='Департамент пользователя', max_length=200, null=True, verbose_name='Департамент пользователя'),
        ),
        migrations.AddField(
            model_name='access',
            name='user_otdel',
            field=models.CharField(blank=True, help_text='Отдел пользователя', max_length=200, null=True, verbose_name='Отдел пользователя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_boss',
            field=models.CharField(blank=True, help_text='Руководитель пользователя', max_length=200, null=True, verbose_name='Руководитель пользователя'),
        ),
    ]
