# Generated by Django 3.0.5 on 2020-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0015_auto_20200420_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='service',
        ),
        migrations.AddField(
            model_name='access',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
    ]
