# Generated by Django 3.0.5 on 2020-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0016_auto_20200420_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='ib_spec',
            field=models.CharField(max_length=200, verbose_name='Руководитель отдела ИБ'),
        ),
        migrations.AlterField(
            model_name='access',
            name='name_user',
            field=models.CharField(max_length=200, verbose_name='Имя Заявителя'),
        ),
        migrations.AlterField(
            model_name='access',
            name='request_desc',
            field=models.TextField(verbose_name='Описание Запроса'),
        ),
        migrations.AlterField(
            model_name='access',
            name='service_owner',
            field=models.CharField(max_length=200, verbose_name='Владелец сервиса'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user_boss',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Руководитель пользователя'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user_dep',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Департамент пользователя'),
        ),
    ]
