# Generated by Django 3.0.5 on 2020-04-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0017_auto_20200420_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='test_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Request_Access.Service'),
        ),
    ]
