# Generated by Django 3.0.5 on 2020-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0018_auto_20200420_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='test_service',
        ),
        migrations.AddField(
            model_name='access',
            name='services',
            field=models.ManyToManyField(to='Request_Access.Service', verbose_name='Сервисы'),
        ),
    ]
