# Generated by Django 3.0.5 on 2020-04-20 13:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0019_auto_20200420_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('На согласовании', 'На согласовании'), ('Согласовано', 'Согласовано'), ('Отказ', 'Заявка отклонена'), ('Ошибка', 'Ошибка'), ('Пипос', 'Пипос')], max_length=46),
        ),
    ]
