# Generated by Django 3.0.5 on 2020-04-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0020_access_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='services',
        ),
    ]
