# Generated by Django 3.0.5 on 2020-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0021_remove_access_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='status',
        ),
        migrations.AddField(
            model_name='access',
            name='services',
            field=models.ManyToManyField(to='Request_Access.Service', verbose_name='Сервисы'),
        ),
    ]
