# Generated by Django 3.0.5 on 2020-04-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0022_auto_20200420_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_owner',
            field=models.BooleanField(default=True, verbose_name='Главный владелец'),
        ),
        migrations.CreateModel(
            name='AproveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_owner', models.CharField(max_length=200, verbose_name='Владелец Сервиса')),
                ('status_request', models.CharField(max_length=200, verbose_name='Статус согласования')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('number_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Access', verbose_name='Номер Заявки')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис')),
            ],
        ),
    ]
