# Generated by Django 3.0.5 on 2020-04-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0023_auto_20200420_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprovelist',
            name='service_name',
        ),
        migrations.AddField(
            model_name='aprovelist',
            name='approve_role',
            field=models.CharField(max_length=200, null=True, verbose_name='Роль согласующего'),
        ),
        migrations.AddField(
            model_name='aprovelist',
            name='approve_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис'),
        ),
        migrations.RemoveField(
            model_name='access',
            name='services',
        ),
        migrations.AddField(
            model_name='access',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис'),
        ),
    ]
