# Generated by Django 3.0.5 on 2020-04-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0025_mails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mails',
            name='document',
        ),
    ]
