# Generated by Django 3.0.5 on 2020-04-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0026_remove_mails_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mails',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='mails',
            name='message',
            field=models.CharField(max_length=20000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mails',
            name='subject',
            field=models.CharField(max_length=1000, verbose_name='Тема письма'),
        ),
    ]
