# Generated by Django 3.0.5 on 2020-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0027_auto_20200421_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='services',
        ),
        migrations.AddField(
            model_name='access',
            name='services',
            field=models.ManyToManyField(to='Request_Access.Service', verbose_name='Сервис'),
        ),
    ]
