# Generated by Django 3.0.5 on 2020-04-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0029_service_service_owner_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_owner_mail',
        ),
    ]
