# Generated by Django 3.0.5 on 2020-04-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0030_remove_service_service_owner_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mails',
            old_name='email',
            new_name='email_address',
        ),
    ]
