# Generated by Django 3.0.5 on 2020-04-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0031_auto_20200421_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='bosses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boss', to='Request_Access.UserProfile')),
                ('userok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.UserProfile')),
            ],
        ),
    ]
