# Generated by Django 3.0.5 on 2020-04-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0032_bosses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bosses',
        ),
    ]
