# Generated by Django 3.0.5 on 2020-04-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0034_userprofile_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_ib_email', models.EmailField(max_length=254, verbose_name='Email Специалиста по ИБ')),
                ('spec_ib_podmena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zam', to='Request_Access.UserProfile', verbose_name='Заместитель специалиста по ИБ')),
                ('specialist_ib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.UserProfile', verbose_name='Специалист Информационной Безопасности')),
            ],
            options={
                'verbose_name': 'Специалисты Информационной Безопасности',
            },
        ),
    ]
