# Generated by Django 3.0.5 on 2020-04-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0035_informationsecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsecurity',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Присвоение'),
            preserve_default=False,
        ),
    ]
