# Generated by Django 3.0.5 on 2020-04-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0036_informationsecurity_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='services',
        ),
        migrations.AddField(
            model_name='access',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис'),
            preserve_default=False,
        ),
    ]
