# Generated by Django 3.0.5 on 2020-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0037_auto_20200421_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='request_statuser',
            field=models.CharField(choices=[('На согласовании у Руководителя', 'На согласовании у Руководителя'), ('Согласовано', 'Согласовано'), ('Отказ', 'Заявка отклонена'), ('Ошибка', 'Ошибка'), ('Пипос', 'Пипос')], default='На согласовании у Руководителя', max_length=100),
        ),
        migrations.AlterField(
            model_name='access',
            name='services',
            field=models.CharField(max_length=200, verbose_name='Сервис'),
        ),
    ]
