# Generated by Django 3.0.5 on 2020-04-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0038_auto_20200421_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис'),
        ),
    ]
