# Generated by Django 3.0.5 on 2020-04-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0039_auto_20200421_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_owner', models.CharField(max_length=200, verbose_name='Владелец Сервиса')),
                ('email_service_owner', models.EmailField(max_length=254, verbose_name='Почта владельца сервиса')),
                ('approve_status_owner', models.CharField(max_length=200, verbose_name='Статус согласования Сервис')),
                ('approve_role', models.CharField(max_length=200, null=True, verbose_name='Роль согласующего')),
                ('email_boss', models.EmailField(max_length=254, verbose_name='Почта руководителя')),
                ('approve_status_boss', models.CharField(max_length=200, verbose_name='Статус согласования руководителя')),
                ('email_ib', models.EmailField(max_length=254, verbose_name='Почта специалиста IB')),
                ('approve_status_ib', models.CharField(max_length=200, verbose_name='Статус согласования руководителя')),
                ('fileserver_owner', models.CharField(blank=True, max_length=200, null=True, verbose_name='Владелец Файловой помойки')),
                ('email_fileserver', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта Владельца Файлового хранилища')),
                ('full_status_request', models.CharField(default='На согласовании', max_length=200, verbose_name='Статус согласования')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('approve_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис')),
                ('ib_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.InformationSecurity', verbose_name='Специалист ИБ')),
                ('number_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Access', verbose_name='Номер Заявки')),
            ],
        ),
        migrations.DeleteModel(
            name='AproveList',
        ),
    ]
