# Generated by Django 3.0.5 on 2020-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0040_auto_20200421_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvelist',
            name='approve_status_boss',
            field=models.CharField(default='Ожидание согласования', max_length=200, verbose_name='Статус согласования руководителя'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='approve_status_ib',
            field=models.CharField(default='Ожидание', max_length=200, verbose_name='Статус согласования руководителя'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='approve_status_owner',
            field=models.CharField(default='Ожидание', max_length=200, verbose_name='Статус согласования Сервис'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='full_status_request',
            field=models.CharField(default='Ожидание согласования руководителя', max_length=200, verbose_name='Статус согласования'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='number_task',
            field=models.CharField(max_length=50, verbose_name='Номер Заявки'),
        ),
    ]
