# Generated by Django 3.0.5 on 2020-04-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0042_auto_20200421_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvelist',
            old_name='approve_role',
            new_name='user_boss',
        ),
        migrations.RemoveField(
            model_name='access',
            name='ib_spec',
        ),
        migrations.RemoveField(
            model_name='access',
            name='service_owner',
        ),
        migrations.RemoveField(
            model_name='access',
            name='services',
        ),
        migrations.RemoveField(
            model_name='access',
            name='user_boss',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='number_task',
        ),
    ]
