# Generated by Django 3.0.5 on 2020-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0043_auto_20200422_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='number_task',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvelist',
            name='number_task',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер заявки'),
            preserve_default=False,
        ),
    ]
