# Generated by Django 3.0.5 on 2020-04-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0044_auto_20200422_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='approve_list',
        ),
        migrations.AlterField(
            model_name='access',
            name='number_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.ApproveList', verbose_name='Номер заявки'),
        ),
    ]
