# Generated by Django 3.0.5 on 2020-04-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0047_auto_20200422_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='approve_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.ApproveList', verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='user_boss',
            field=models.CharField(max_length=200, null=True, verbose_name='Руководитель пользователя'),
        ),
    ]
