# Generated by Django 3.0.5 on 2020-04-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0048_auto_20200426_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_dep',
            field=models.CharField(blank=True, help_text='Департамент', max_length=200, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_last_name',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_otdel',
            field=models.CharField(blank=True, help_text='Отдел', max_length=200, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_second_name',
            field=models.CharField(blank=True, help_text='Отчество', max_length=200, verbose_name='Отчество'),
        ),
    ]
