# Generated by Django 3.0.5 on 2020-04-27 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Request_Access', '0049_auto_20200426_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='name_user',
        ),
        migrations.AddField(
            model_name='access',
            name='author',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя Заявителя'),
        ),
    ]
