# Generated by Django 3.0.5 on 2020-04-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0050_auto_20200427_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='access',
            name='approve_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.ApproveList', verbose_name='Лист Согласования'),
        ),
    ]
