# Generated by Django 3.0.5 on 2020-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0051_auto_20200427_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Внутренний телефон'),
        ),
    ]
