# Generated by Django 3.0.5 on 2020-04-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0053_userprofile_user_boss2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_boss',
        ),
    ]
