# Generated by Django 3.0.5 on 2020-04-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0054_remove_userprofile_user_boss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_boss2',
            new_name='user_boss',
        ),
    ]
