# Generated by Django 3.0.5 on 2020-04-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Request_Access', '0057_auto_20200430_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsecurity',
            name='spec_ib_podmena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zam', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель специалиста по ИБ'),
        ),
        migrations.AlterField(
            model_name='informationsecurity',
            name='specialist_ib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Специалист Информационной Безопасности'),
        ),
    ]
