# Generated by Django 3.0.5 on 2020-06-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0060_service_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_group',
            name='service',
        ),
        migrations.AddField(
            model_name='service_group',
            name='service',
            field=models.ManyToManyField(null=True, to='Request_Access.Service'),
        ),
    ]
