# Generated by Django 3.0.5 on 2020-06-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0061_auto_20200629_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_group',
            options={'verbose_name': 'Сервисная группа', 'verbose_name_plural': 'Сервисные группы'},
        ),
    ]
