# Generated by Django 3.0.5 on 2020-06-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0062_auto_20200629_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_group',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='service_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service_Group'),
        ),
    ]
