# Generated by Django 3.0.5 on 2020-06-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0063_auto_20200629_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accepter_FIO', models.CharField(max_length=200, verbose_name='Согласующее лицо')),
                ('Email_Accepter', models.EmailField(max_length=254, verbose_name='Почта согласующего')),
                ('Accepter_Status', models.CharField(default='Ожидание', max_length=200, verbose_name='Статус согласования Сервис')),
                ('Accepted_Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис для согласования')),
                ('Access_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Access', verbose_name='Номер Заявки')),
            ],
        ),
    ]
