# Generated by Django 3.0.5 on 2020-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0064_list_of_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_accept',
            name='Accepted_Service',
        ),
        migrations.AddField(
            model_name='list_of_accept',
            name='Accepted_Service',
            field=models.ManyToManyField(null=True, to='Request_Access.Service', verbose_name='Сервис для согласования'),
        ),
    ]
