# Generated by Django 3.0.5 on 2020-06-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0067_auto_20200629_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_accept',
            name='Accepted_Service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис для согласования'),
        ),
    ]
