# Generated by Django 3.0.5 on 2020-07-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0068_auto_20200629_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_accept',
            name='Accepted_Service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис для согласования'),
            preserve_default=False,
        ),
    ]
