# Generated by Django 3.0.5 on 2020-07-02 09:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0070_list_of_accept_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_accept',
            name='test',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'АСУ ВП'), (2, '1С Русагротранс'), (3, 'АСУ ТК'), (4, 'Файловое Хранилище'), (5, 'Удаленный доступ'), (6, 'Русагротранс Онлайн')], default=1, max_length=11),
            preserve_default=False,
        ),
    ]
