# Generated by Django 3.0.5 on 2020-07-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0071_auto_20200702_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_accept',
            name='test',
        ),
        migrations.AlterField(
            model_name='list_of_accept',
            name='Accepted_Service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Service', verbose_name='Сервис для согласования'),
        ),
        migrations.AlterField(
            model_name='list_of_accept',
            name='Accepter_FIO',
            field=models.CharField(default='Иванов Иван Иванович', max_length=200, verbose_name='Согласующее лицо'),
        ),
        migrations.AlterField(
            model_name='list_of_accept',
            name='Access_ID',
            field=models.ForeignKey(blank=True, default=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='Request_Access.Access', verbose_name='Номер Заявки'),
        ),
        migrations.AlterField(
            model_name='list_of_accept',
            name='Email_Accepter',
            field=models.EmailField(default='123@mail.rus', max_length=254, verbose_name='Почта согласующего'),
        ),
    ]
