# Generated by Django 3.0.5 on 2020-07-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0072_auto_20200702_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvelist',
            name='approve_service',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='approve_status_owner',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='email_fileserver',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='email_service_owner',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='fileserver_owner',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='full_status_request',
        ),
        migrations.RemoveField(
            model_name='approvelist',
            name='service_owner',
        ),
    ]
