# Generated by Django 3.0.7 on 2020-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0075_auto_20200716_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_full_name', models.CharField(max_length=1000, verbose_name='Полное имя компании')),
                ('company_short_name', models.CharField(max_length=1000, verbose_name='Короткое имя компании')),
                ('company_address', models.CharField(max_length=2000, verbose_name='Юридический адрес Компании')),
                ('company_post_address', models.CharField(max_length=2000, verbose_name='Почтовый адрес Компании')),
                ('company_telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон компании')),
                ('company_order', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер договора с компанией')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Заявка на доступ', 'verbose_name_plural': 'Запросы на доступ'},
        ),
        migrations.AlterModelOptions(
            name='approvelist',
            options={'verbose_name': 'Лист согласования ИБ и Руководителя', 'verbose_name_plural': 'Листы согласования ИБ и Руководителя'},
        ),
        migrations.AlterModelOptions(
            name='list_of_accept',
            options={'verbose_name': 'Лист согласования сервисов', 'verbose_name_plural': 'Листы согласования сервисов'},
        ),
        migrations.AlterModelOptions(
            name='mails',
            options={'verbose_name': 'Почтовое сообщение', 'verbose_name_plural': 'Почтовые сообщения'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Тестовый Запрос', 'verbose_name_plural': 'Тестовые Запросы'},
        ),
    ]
