# Generated by Django 3.0.5 on 2020-07-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0077_auto_20200722_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='company_inn',
            field=models.CharField(default=0, max_length=30, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='company_kpp',
            field=models.CharField(default=0, max_length=1000, verbose_name='КПП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companys',
            name='company_activator',
            field=models.BooleanField(blank=True, default=False, help_text='Установка триггера владельца портала', null=True, verbose_name='Владелец портала'),
        ),
    ]
