# Generated by Django 3.0.7 on 2020-07-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Access', '0078_auto_20200724_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='email_cc',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Копии получателей'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='approve_status_boss',
            field=models.CharField(blank=True, default='Ожидание согласования', max_length=200, null=True, verbose_name='Статус согласования руководителя'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='email_boss',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта руководителя'),
        ),
        migrations.AlterField(
            model_name='approvelist',
            name='user_boss',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Руководитель пользователя'),
        ),
        migrations.CreateModel(
            name='OuterApproveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ib', models.EmailField(max_length=254, verbose_name='Почта специалиста IB')),
                ('approve_status_ib', models.CharField(default='Ожидание', max_length=200, verbose_name='Статус согласования руководителя')),
                ('full_status_request', models.CharField(default='Ожидание согласования руководителя', max_length=200, verbose_name='Статус согласования')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('ib_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request_Access.InformationSecurity', verbose_name='Специалист ИБ')),
            ],
            options={
                'verbose_name': 'Лист согласования ИБ и Руководителя',
                'verbose_name_plural': 'Листы согласования ИБ и Руководителя',
            },
        ),
    ]
