# Generated by Django 3.0.7 on 2020-08-18 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Request_Access', '0082_auto_20200818_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_deps',
            new_name='RootFilepath',
        ),
    ]
